### ISSUE TITLE
Are Sub-Menu supported?

### ISSUE THREAD

**Issue by Scoubi** [clente/hugo-bearcub#22]
I would like to have sub-menu on my site. 

Something like 
About -> FAQ
About -> Contact Us
Main1 -> Sub1
Main1 -> Sub2

Does the theme support this ?

Thank you.

**Comment by clente** [comment]
You'd have to edit the code yourself for that. The base theme doesn't have support for this.

**Comment by Scoubi** [comment]
Ok, I've made it work. 
I could make a PR if it's useful for other. 
The way I made it, the original menu still works and it's the same color and way to manage the entry (all in the markdown header). 
![menu](https://github.com/user-attachments/assets/78545d01-af08-4080-b7b7-e0eb87f747e6)

```
---
title: "Contact"
menu: 
  main:
    parent: "About"
    name: "Contact"
    weight: 2
---
```
